# Generated by Django 4.2.13 on 2024-06-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_auto_20240619_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
