# Generated by Django 4.2.13 on 2024-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_auto_20240620_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
